# fly.toml app configuration file generated for app-green-hill-6606 on 2024-10-14T20:12:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-green-hill-6606'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
